default/objects/Case_line_Item__c/Case_line_Item__c.object-meta.xml
<CustomObject>
    <label>Case line Item</label>
    <nameField>
        <displayFormat>CLI-{000000}</displayFormat>
        <label>Case line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Case_line_Item__c/fields/Affected_Part_No__c.field-meta.xml
<CustomField>
    <fullName>Affected_Part_No__c</fullName>
    <label>Affected Part No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case_line_Item__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case line Items</relationshipLabel>
    <relationshipName>Case_line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Case_line_Item__c/fields/Machine_No__c.field-meta.xml
<CustomField>
    <fullName>Machine_No__c</fullName>
    <label>Machine No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case_line_Item__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case_line_Item__c/fields/Part_Sl_No_Batch_No__c.field-meta.xml
<CustomField>
    <fullName>Part_Sl_No_Batch_No__c</fullName>
    <label>Part Sl.No. /Batch No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case_line_Item__c/fields/Problem__c.field-meta.xml
<CustomField>
    <fullName>Problem__c</fullName>
    <label>Problem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/caseOEMTemplate.cls
public class caseOEMTemplate {

    public Id caseId {get;set;}
    public List<Case_line_Item__c> getcaseLineItemsfunction()
    {
        System.debug('caseId::'+caseId);
        List<Case_line_Item__c> caseLineItems;
        caseLineItems = [SELECT Id, Model__c, Machine_No__c,Problem__c, Quantity__c,Part_Name__c, Affected_Part_No__c, Part_Sl_No_Batch_No__c FROM Case_line_Item__c WHERE Case__c	 =: caseId];
        System.debug('caseLineItems::'+caseLineItems);
        return caseLineItems;
    }
    
}