default/objects/Case_line_Item__c/Case_line_Item__c.object-meta.xml
<CustomObject>
    <label>Case line Item</label>
    <nameField>
        <displayFormat>CLI-{000000}</displayFormat>
        <label>Case line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Case_line_Item__c/fields/Affected_Part_No__c.field-meta.xml
<CustomField>
    <fullName>Affected_Part_No__c</fullName>
    <label>Affected Part No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case_line_Item__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Case line Items</relationshipLabel>
    <relationshipName>Case_line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Case_line_Item__c/fields/Machine_No__c.field-meta.xml
<CustomField>
    <fullName>Machine_No__c</fullName>
    <label>Machine No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case_line_Item__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case_line_Item__c/fields/Part_Sl_No_Batch_No__c.field-meta.xml
<CustomField>
    <fullName>Part_Sl_No_Batch_No__c</fullName>
    <label>Part Sl.No. /Batch No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Case_line_Item__c/fields/Problem__c.field-meta.xml
<CustomField>
    <fullName>Problem__c</fullName>
    <label>Problem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/classes/CaselineItemTriggerHandler.cls
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------
Description     : Trigger for Case_line_Item__c
Inputs          : WorkOCase_line_Item__crder that are being triggered
Test Classes    : CaselineItemTriggerHandlerTest
Created         : 16-11-2021
---------------------------------------------------------------------------------------------------------------------------------------------------------------*/
public class CaselineItemTriggerHandler {
    
    /* PURPOSE : AfterInsert
* PARAM    : Map of WorkOrder
* RETURNS  : 
*/
    public static void afterUpdate(Map<ID,Case_line_Item__c> newCaselineItemMap){
        createCaseWorkOrderLineItems(newCaselineItemMap);
    }
    
    /* PURPOSE : Create WorkOrderLineItems if present on Parent Case
* PARAM    : Map of WorkOrder
* RETURNS  : 
*/
    public static void createCaseWorkOrderLineItems(Map<ID,Case_line_Item__c> newCaselineItemMap){
        
        Map<Id, WorkOrderLineItem> workOrderLineItemsMap = new  Map<Id, WorkOrderLineItem>([SELECT ID , Case_line_Item__c, AssetId, Problem__c, Affected_Part_No__c, Machine_No__c, Model__c,
                                                                                            Part_Name__c, Part_Sl_No_Batch_No__c, Quantity__c
                                                                                            FROM WorkOrderLineItem
                                                                                            WHERE Case_line_Item__c IN : newCaselineItemMap.KeySet()]);
        
        
        
        if(!workOrderLineItemsMap.isEmpty()){
            
            List<WorkOrderLineItem> workOrderLineUpdateList = new List<WorkOrderLineItem>();
            
            for(WorkOrderLineItem workOrderLineRecord : workOrderLineItemsMap.values()){
                if(workOrderLineRecord.AssetId != newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Asset__c ||
                   workOrderLineRecord.Problem__c != newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Problem__c ||
                   workOrderLineRecord.Affected_Part_No__c != newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Affected_Part_No__c ||
                   workOrderLineRecord.Machine_No__c != newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Machine_No__c ||
                   workOrderLineRecord.Model__c != newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Model__c ||
                   workOrderLineRecord.Part_Name__c != newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Part_Name__c ||
                   workOrderLineRecord.Part_Sl_No_Batch_No__c != newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Part_Sl_No_Batch_No__c ||
                   workOrderLineRecord.Quantity__c != newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Quantity__c
                   
                  ){
                      
                      WorkOrderLineItem workOrderLineItem = new WorkOrderLineItem();
                      workOrderLineItem.Id= workOrderLineRecord.Id;
                      workOrderLineItem.AssetId = newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Asset__c;
                      workOrderLineItem.Problem__c = newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Problem__c;
                      workOrderLineItem.Affected_Part_No__c = newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Affected_Part_No__c;
                      workOrderLineItem.Machine_No__c = newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Machine_No__c;
                      workOrderLineItem.Model__c = newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Model__c;
                      workOrderLineItem.Part_Name__c = newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Part_Name__c;
                      workOrderLineItem.Part_Sl_No_Batch_No__c = newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Part_Sl_No_Batch_No__c;
                      workOrderLineItem.Quantity__c	 = newCaselineItemMap.get(workOrderLineRecord.Case_line_Item__c).Quantity__c;
                      
                      workOrderLineUpdateList.add(workOrderLineItem);
                      
                      System.debug('Work Order added to updated List');
                      
                  }
                
            }
            
            System.debug('workOrderLineUpdateList::'+workOrderLineUpdateList);
            System.debug('workOrderLineUpdateList  SIZE::'+workOrderLineUpdateList.Size());
            
            if(!workOrderLineUpdateList.IsEmpty()){
                UPDATE workOrderLineUpdateList;
            }
            
        }
        
    }
    
}