default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Commission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Commission__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Commission__c/fields/Sales_Agent__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agent</label>
    <referenceTo>Sales_Agent__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Sales_Agent__c/Sales_Agent__c.object-meta.xml
<CustomObject>
    <description>Sales Agent Object For Technical Assessment Given By Ajit Sir.</description>
    <label>Sales Agent</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Sales Agent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Sales_Agent__c/fields/Default_Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Default_Commission_Rate__c</fullName>
    <label>Default Commission Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/classes/SalesAgentRecords.cls
public  class SalesAgentRecords {
    @AuraEnabled(cacheable=true)   
    public static List<Sales_Agent__c> getSalesAgents(Id lwcRecordId) { 
        Set<Id> agentIdSet = new Set<Id>();
        for(Commission__c commission :[SELECT Name,Sales_Agent__c FROM Commission__c
                                        WHERE Commission__c.Opportunity__c =: lwcRecordId]){
                                            agentIdSet.add(commission.Sales_Agent__c);  
                                        }
        return [SELECT Id, Name, Default_Commission_Rate__c 
                FROM Sales_Agent__c
                 WHERE Id NOT In : agentIdSet];    
    }   
    @AuraEnabled  
    public static void createCommissions(List<Id> selCommissionId, Id lwcRecordId){
                                        
        
        List<Sales_Agent__c> SaList = new List<Sales_Agent__c>();
        SaList = [SELECT Id FROM Sales_Agent__c WHERE Id  =: selCommissionId];
            List<Commission__c> com = new List<Commission__c>();
            for(integer i=0; i<SaList.size(); i++){
                 Commission__c comm = new Commission__c(); 
                 comm.Sales_Agent__c = SaList[i].Id;
                 comm.Opportunity__c = lwcRecordId; 
                 com.add(comm);
            }
            INSERT com; 
    }    
}