default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Commission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Commission__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <formula>IF( Overridden_Rate__c &gt; 0, Opportunity__r.Amount *   Overridden_Rate__c , Opportunity__r.Amount *  Sales_Agent__r.Default_Commission_Rate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Commission__c/fields/Commission_Name__c.field-meta.xml
<CustomField>
    <fullName>Commission_Name__c</fullName>
    <label>Commission Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

default/objects/Commission__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Commission__c/fields/Overridden_Rate__c.field-meta.xml
<CustomField>
    <fullName>Overridden_Rate__c</fullName>
    <label>Overridden Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

default/objects/Commission__c/fields/Sales_Agent__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agent</label>
    <referenceTo>Sales_Agent__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Sales_Agent__c/Sales_Agent__c.object-meta.xml
<CustomObject>
    <description>Sales Agent Object For Technical Assessment Given By Ajit Sir.</description>
    <label>Sales Agent</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Sales Agent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/CommRecords.cls
public class CommRecords {
    @AuraEnabled(cacheable=true) 
    public static List<Commission__c> getCommissions(Id lwcRecordId) {
        return [SELECT Id, Name,Commission_Name__c,Commission_Amount__c, Opportunity__c, Overridden_Rate__c,
        Sales_Agent__c ,Sales_Agent__r.Name 
        FROM Commission__c  
        WHERE Opportunity__r.Id =: lwcRecordId];        
    } 
  
    @AuraEnabled  
    public static void deleteSelectedCommission(List<Id> selCommissionId) {
        List<Commission__c> commList = new List<Commission__c>();
        commList = [SELECT Id FROM Commission__c 
                            WHERE Id In :selCommissionId]; 
            if(commList!=Null && commList.size()>0){
                delete commList; 
            }         
    } 
}  