default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>Custom Student Object</description>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Student__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M.Tech</fullName>
            </value>
            <value>
                <fullName>B.Tech</fullName>
            </value>
            <value>
                <fullName>Mca</fullName>
            </value>
            <value>
                <fullName>Msc</fullName>
            </value>
            <value>
                <fullName>Mba</fullName>
            </value>
            <value>
                <fullName>Bca</fullName>
            </value>
            <value>
                <fullName>Bsc</fullName>
            </value>
            <value>
                <fullName>Bba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Student__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/classes/Email.cls
public class Email {
    public static void main(){
        
     //Fetch Student object records
        
     List<Student__c> StudentList = new List<Student__c>();
     StudentList = [select name,email__c,phone__c,address__c,State__c,Course__c from student__c 
                            WHERE State__c='Maharashtra' AND course__c='M.Tech'];
      
     //Create a list of comma saperated values
     
      List<String> StudentDetails = new List<String>();
        if(StudentList != NULL && !StudentList.isEmpty()){
            for(Student__c StudObj : StudentList){
                StudentDetails.add(StudObj.name + ',' + StudObj.email__c + ',' + StudObj.address__c);                
            }
        }   
      //Creating CSV File
      
      String csvFile;
      String csvColumnHeader = 'Name, Email, Address, State, Course\n';
      List<String> csvRowValues = new List<String>();
      csvFile = csvColumnHeader + String.join(StudentDetails,'\n');
         
      //Create Attachment
      
      Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
      attach.setContentType('text/csv');
      attach.setFileName('Student file.csv');
      attach.setInline(true);
      attach.body = Blob.valueOf(csvFile);
        
      //Creating Recipient list
      
      List<String>recipientList = new List<String>();
      recipientList.add('pradhunya@dreamwares.com');
        
      //Sending Mail And Attach the csv File
      
      List<Messaging.SingleEmailMessage> mailsList = new List<Messaging.SingleEmailMessage>();
      Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
      Mail.setToAddresses(recipientList);
      Mail.setSubject('Details Of Students');
      String body = 'Please find the attachment...';
      mail.setHtmlBody(body);
        if(attach != NULL){
            mail.setFileAttachments(new Messaging.EmailFileAttachment[] { attach });
        }
        mailsList.add(mail);
        Messaging.SendEmailResult[] SendEmailResults= Messaging.sendEmail(mailsList);     
     
	}
}