default/objects/TextBom__c/TextBom__c.object-meta.xml
<CustomObject>
    <label>TextBom</label>
    <nameField>
        <displayFormat>TBOM-{0000000}</displayFormat>
        <label>TextBom Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TextBoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/TextBom__c/fields/Bom_Content__c.field-meta.xml
<CustomField>
    <fullName>Bom_Content__c</fullName>
    <label>Bom Content</label>
    <length>120000</length>
    <type>Html</type>
</CustomField>

default/objects/TextBom__c/fields/Characteristic_Description__c.field-meta.xml
<CustomField>
    <fullName>Characteristic_Description__c</fullName>
    <label>Characteristic Description</label>
    <type>TextArea</type>
</CustomField>

default/objects/TextBom__c/fields/Characteristic_No__c.field-meta.xml
<CustomField>
    <fullName>Characteristic_No__c</fullName>
    <description>Product Attribute</description>
    <label>Characteristic No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/TextBom__c/fields/Characteristic_Value__c.field-meta.xml
<CustomField>
    <fullName>Characteristic_Value__c</fullName>
    <description>Attribute value</description>
    <label>Characteristic Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/TextBom__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <description>Product FG Code</description>
    <inlineHelpText>Product FG Code</inlineHelpText>
    <label>Material</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

default/classes/TextBomHelper.cls
/**  
 * @Description        : Helper class for TextBom
 * @Author             : NA
 * @Date               : 19-01-2022 (DD-MM-YYYY)
 * @TestClass          : TextBomHelperTest.cls
 * 
 * Modification Log:
 * Ticket           Author          Date                 Description
 * NA               NA              19-01-2022           Initial Development
*/

public class TextBomHelper {

    public static List<TextBom__c> searchTextBom(Boolean isStrictMatch, String materialCode, Map<String, String> charMap) {
        List<TextBom__c> textBomList = new List<TextBom__c>();

        if (isStrictMatch) {
            List<String> charNoList = new List<String>();
            for (String charNo : charMap.keySet()) {
                charNoList.add(charNo);
            }
            String mergedCharNo = String.join(charNoList, ' and ');
            String mergedCharVals = String.join(charMap.values(), ' and ');
            textBomList = [SELECT Id, Bom_Content__c, Characteristic_Description__c
                           FROM TextBom__c
                           WHERE Material__c = :materialCode                           
                           AND Characteristic_No__c = :mergedCharNo
                           AND Characteristic_Value__c = :mergedCharVals];
        } else {
            // TODO: 2nd version of Search Logic 
            // 1. Generate all permutations of CharNo & CharVal
            // 2. Apply CharNo & CharVal as Array in SOQL
            // 3. Sort the result based on Highest no of combination on top
        }

        return textBomList;
    }
}