default/objects/Tools__c/Tools__c.object-meta.xml
<CustomObject>
    <label>Tools</label>
    <nameField>
        <label>Tools Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Tools__c/fields/Issued_quantity__c.field-meta.xml
<CustomField>
    <fullName>Issued_quantity__c</fullName>
    <label>Issued quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Tools_Assignment__c/Tools_Assignment__c.object-meta.xml
<CustomObject>
    <label>Tools Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Tools Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tools Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Tools_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Tools_Assignment__c/fields/Tools__c.field-meta.xml
<CustomField>
    <fullName>Tools__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tools</label>
    <referenceTo>Tools__c</referenceTo>
    <relationshipLabel>Tools Assignments</relationshipLabel>
    <relationshipName>Tools_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/classes/ToolsAssignmentTriggerHandler.cls
public class ToolsAssignmentTriggerHandler {
    public static void afterInsert(List<Tools_Assignment__c> newToolsAssignmentList){
        toolsAssignmentQuantityCount(newToolsAssignmentList);
    }
    public static void afterDelete(List<Tools_Assignment__c> newToolsAssignmentList){
        toolsAssignmentQuantityCount(newToolsAssignmentList);
    }
    public static void afterUpdate(List<Tools_Assignment__c> newToolsAssignmentList){
        toolsAssignmentQuantityCount(newToolsAssignmentList);
    }
    
    public static void toolsAssignmentQuantityCount(List<Tools_Assignment__c> newToolsAssignmentList){
        
        
        Set<String> toolsIdSet= new Set<String>();
        //Get Tools Ids
        for(Tools_Assignment__c record:newToolsAssignmentList){
          toolsIdSet.add(record.Tools__c);
        }
        
        /*
        
        if(newToolsAssignmentList!=Null && !newToolsAssignmentList.isEmpty()){
            
            newToolsAssignmentList=[Select Id,Status__c, Returned__c
                                    FROM Tools_Assignment__c
                                    WHERE Tools__c IN:toolsIdSet AND Status__c='Approved' AND Returned__c= False];
        }
        System.debug('Tools Ids::'+toolsIdSet);
        System.debug('List Of TA::'+newToolsAssignmentList);
        */
        
        AggregateResult[] groupedResults;
        groupedResults=[SELECT Tools__c, SUM(Quantity__c)quantity 
                        FROM Tools_Assignment__c 
                        Where Tools__c IN:toolsIdSet AND Status__c='Approved' AND Returned__c= False GROUP BY Tools__c];
        
       
        List<Tools__c> updateToolsList=new List<Tools__c>();
        
        System.debug('Outside For Loop::');
            
        for(AggregateResult ar:groupedResults){
            System.debug('Inside For Loop::');
            Tools__c toolsRec= new Tools__c();
            toolsRec.Id= (Id)ar.get('Tools__c');
            toolsRec.Issued_quantity__c=(Decimal)ar.get('quantity')==Null?0:(Decimal)ar.get('quantity');
            System.debug('Issue quantity::'+toolsRec.Issued_quantity__c);
            /*if(groupedResults.isEmpty()){
                toolsRec.Issued_quantity__c=0;
                System.debug('Issue quantity::'+toolsRec.Issued_quantity__c);
            }*/
       
            updateToolsList.add(toolsRec);
        }
        
        if(groupedResults.isEmpty()){
            for(Id toolId :toolsIdSet){
                Tools__c tool = new Tools__c();
                tool.Id = toolId;
                tool.Issued_quantity__c = 0;
                
                updateToolsList.add(tool);
            }
        }
        
       if(!updateToolsList.isEmpty()){
            try{
                
            Update updateToolsList;
            }
            catch(DMLException ex){
                newToolsAssignmentList[0].addError(ex.getDmlMessage(0));
            }
        }
        System.debug('Updated List::'+updateToolsList);
        System.debug('Updated List Size::'+updateToolsList.Size());
        
    }    
}