default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Dummy object for Assignment 21</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Application__c/fields/Ammount__c.field-meta.xml
<CustomField>
    <fullName>Ammount__c</fullName>
    <label>Ammount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Application__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Custom Class Object</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Class__c/fields/Class_Country__c.field-meta.xml
<CustomField>
    <fullName>Class_Country__c</fullName>
    <label>Class Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country1</valueSetName>
    </valueSet>
</CustomField>

default/objects/Class__c/fields/Sub__c.field-meta.xml
<CustomField>
    <fullName>Sub__c</fullName>
    <label>Sub</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Standard__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marathi</fullName>
            </value>
            <value>
                <fullName>Geography</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Drawing</fullName>
            </value>
            <value>
                <fullName>Math</fullName>
            </value>
            <value>
                <fullName>Eng</fullName>
            </value>
            <value>
                <fullName>Social Science</fullName>
            </value>
            <value>
                <fullName>Physics</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Mathematics</fullName>
            </value>
            <value>
                <fullName>Physics-2</fullName>
            </value>
            <value>
                <fullName>Chemestry-2</fullName>
            </value>
            <value>
                <fullName>Mathematics-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/O1__c/O1__c.object-meta.xml
<CustomObject>
    <label>ObjectOne</label>
    <nameField>
        <label>O1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectOnes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/ObjectThree__c/ObjectThree__c.object-meta.xml
<CustomObject>
    <label>ObjectThree</label>
    <nameField>
        <label>ObjectThree Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectThrees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/ObjectThree__c/fields/ObjectTwo__c.field-meta.xml
<CustomField>
    <fullName>ObjectTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ObjectTwo</label>
    <referenceTo>ObjectTwo__c</referenceTo>
    <relationshipLabel>ObjectThrees</relationshipLabel>
    <relationshipName>ObjectThrees</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/ObjectTwo__c/ObjectTwo__c.object-meta.xml
<CustomObject>
    <label>ObjectTwo</label>
    <nameField>
        <label>ObjectTwo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectTwos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/ObjectTwo__c/fields/ObjectOne__c.field-meta.xml
<CustomField>
    <fullName>ObjectOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ObjectOne</label>
    <referenceTo>O1__c</referenceTo>
    <relationshipLabel>ObjectTwos</relationshipLabel>
    <relationshipName>ObjectTwos</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/RelationShip.cls
public class RelationShip {
    Public static void main(){
        //***Child to parent
        
        //***Standard object
        List<Contact> conList = [select FirstName,LastName,Account.Name,Account.NumberOfEmployees from Contact];
        
        //***Custom Object
        List<Application__c> appList = [select Name,Ammount__c,Class__r.Name,Class__r.Description__c from Application__c];
        
        //***Parent to child
        
        //***Standard object
        List<Account>accList=[select name,NumberOfEmployees,(select lastname,phone,email from contacts) From account];
        System.debug(accList);
        
        //***Custom object
        List<Class__c>cList=[select name,Class_Country__c,Sub__c,(select name,Account__c from applications__r)from class__c];
        System.debug(cList);
        
        //***Multilevel Relatioship
        
        //***Standard Object              
        
        //***1st Option
        //Account
        //       Opportunity
        //                  OpportunityLineItems=> Query
        
        List<OpportunityLineItem>oppLineItem=[Select name,quantity,Opportunity.name,
                                             Opportunity.amount,
                                             opportunity.Account.name,
                                             opportunity.account.NumberOfEmployees 
                                             from opportunityLineItem];
        
        //***2nd Option
       //Account
       //       Opportunity=>Query
       //                  OpportunityLineItems=> Query
                         
        List<Opportunity>oppList=[Select Name,Amount,Account.Name,Account.NumberOfEmployees,
                                  (Select Name,quantity from opportunityLineitems)from opportunity];
        
        
        //***Custom Object              
        
        //***1st Option
        //ObjectOne__c 
        //            ObjectTwo__c
        //                        ObjectThree=> Query
        
       List<ObjectThree__c> O3List = [Select Name,ObjectTwo__r.Name,ObjectTwo__r.ObjectOne__r.Name from ObjectThree__c]; 
       
      //***2nd Option
        //ObjectOne__c
        //            ObjectTwo__c=> Query
        //                        ObjectThree
       
        
       List<ObjectTwo__c> O2List = [Select Name,ObjectOne__r.Name,(Select Name from ObjectThrees__r) from ObjectTwo__c];
        
            
            
                                             
        
    }

}