default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Exception_Log__c/fields/Log_In_User__c.field-meta.xml
<CustomField>
    <fullName>Log_In_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log In User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exception_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Exception_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Error Log</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

default/objects/Exception_Log__c/fields/Notify_Admin__c.field-meta.xml
<CustomField>
    <fullName>Notify_Admin__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notify Admin</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Exception_Log__c/fields/Related_To_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Record_Id__c</fullName>
    <label>Related To Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Exception_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Name Of The Class From Exception Raise</description>
    <label>Source</label>
    <type>TextArea</type>
</CustomField>

default/classes/ExceptionUtility.cls
public class ExceptionUtility {
	static List<Exception_Log__c> logs = new List<Exception_Log__c>();
    
    public static void addExceptionLog(List<LogUitlity> exceptionLog){
        if(exceptionLog != null && !exceptionLog.isEmpty()){
            for(LogUitlity log : exceptionLog){
                addExceptionLog(log);
            }
        }
    } 
    
    public static void addExceptionLog(LogUitlity exceptionLog){
        if(exceptionLog != null){
            Exception_Log__c debugLog = new Exception_Log__c();
            debugLog.Name = exceptionLog.className +' '+ exceptionLog.exceptionType;
            debugLog.Related_To_Record_Id__c = exceptionLog.recordId;
            debugLog.StackTrace__c = exceptionLog.stackTrace;
            debugLog.Source__c = exceptionLog.className;
            debugLog.MethodName__c = exceptionLog.methodName;
            debugLog.Exception_Type__c = exceptionLog.exceptionType;
            debugLog.Line_Number__c = exceptionLog.lineNumber;
            debugLog.Log_In_User__c = UserInfo.getUserId();
            debugLog.Message__c = exceptionLog.message;
            debugLog.Notify_Admin__c = true;
            logs.add(debugLog);
        }
    }
    
    public static void commiLog(){
            if( logs != null){
                insert logs;
                //DataBase.SaveResult[] result = Database.insert(logs);
                //if()
            }
    }
    
    public class LogUitlity{
        String recordId;
        String className;
        String methodName;
        String stackTrace;
        String message;
        String exceptionType;
        Integer lineNumber;
        
        public LogUitlity(String recordId, String className, String methodName, String stackTrace, String message, String exceptionType, Integer lineNumber){
            this.recordId = recordId;
            this.className = className;
            this.methodName = methodName;
            this.stackTrace = stackTrace;
            this.message = message;
            this.exceptionType = exceptionType;
            this.lineNumber = lineNumber;  
           
        }       
    }

}